### ISSUE TITLE
Cannot run docker containers

### ISSUE THREAD

**Issue by anujluthra** [futurexv2016/url-shortener#1]
From project root, when following instructions in README, 
`cd deploy && ./startAll` 
it gives following errors and fails to build backend:

```
ERROR: .FileNotFoundError: [Errno 2] No such file or directory: './local.yml'
Docker Compose is now in the Docker CLI, try `docker compose up`

backend_1   | Error: Unable to access jarfile app.jar
url-shortener_backend_1 exited with code 1
```

**Comment by futurexv2016** [comment]
Hi Anuj,

Checking out the code and try to reproduce your error but I cannot get it

However, there is an issue that I changed the name of APIFilterLogging
class to be more meaningful but the commit before was wrong.

Wrong commit:
https://github.com/futurexv2016/url-shortener/commit/4b5e990a0955ed196e3af5c3981fc906016a794b
Fixed commit:
https://github.com/futurexv2016/url-shortener/commit/bf934adf3a05445f8e544f21ac70f13560b7183a

Could you redeploy again and let me know if any issues are left?

I have tested it carefully before but did not test it again since I thought
that class name change did not impact, sorry for this basic error.

You can contact me via email or my skype (minh_ho_2013) to realtime
support. I would be online 24/7.

Once again, sorry for this inconvenience

Regards,
David Ho

**Comment by anujluthra** [comment]
Looks like that commit fixed the problem and docker is now booting up the application properly. Thanks for fixing it quickly.
